# Generated by Django 3.2 on 2021-05-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_item_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.CharField(choices=[('BA', 'baixa'), ('ME', 'média'), ('AL', 'alta')], default='ME', max_length=2),
        ),
    ]
